# Generated by Django 5.1.3 on 2024-12-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
