# Generated by Django 5.1.3 on 2024-12-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='card_info',
        ),
    ]
