# Generated by Django 5.1.3 on 2024-12-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_instock_product_quantity_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(choices=[('delivery', 'Payment for delivery'), ('pickup', 'Picking up in shop'), ('lay_buy', 'Paying a fraction (lay buy)'), ('pay_in_shop', 'Pay the complete money in shop physically')], default='delivery', max_length=20),
        ),
    ]
