# Generated by Django 5.1.3 on 2025-02-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='Admin_rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
