# Generated by Django 5.1.3 on 2025-02-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_aboutus_contactus_relatedproductimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us Entries'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_images/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default="Welcome to One-Stop Afroshop, an African shop in Germany dedicated \n        to bringing the vibrant and diverse flavors of Africa right to your doorstep. \n        We specialize in offering a wide range of authentic African products, from \n        traditional food ingredients to beauty and skincare products that celebrate \n        the rich cultures and heritage of the African continent.\n\n        Our mission is to connect the African diaspora in Germany with the products \n        they love and miss from home. Whether you're craving a taste of home with \n        our diverse range of African food products or looking for high-quality \n        cosmetics made with natural African ingredients, we've got something for \n        everyone.\n\n        We are passionate about sharing the essence of African culture through our \n        products, offering you a one-stop shop for all things African. We pride \n        ourselves on quality, authenticity, and a deep commitment to customer \n        satisfaction. As we continue to grow, we aim to expand our product range \n        and provide even more opportunities to experience the best of Africa \n        right here in Germany.\n        "),
        ),
    ]
