# Generated by Django 5.1.3 on 2025-02-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_aboutus_options_aboutus_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
