# Generated by Django 5.1.3 on 2025-02-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_parket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parket_price',
            new_name='bulk_pirce',
        ),
    ]
